### PR TITLE
yoshino: add kryo cpu variant

### PR DESCRIPTION
**Pull request by alviteri**
actually aosp doesn't offer kryo cpu optimizations
add this flag for roms which support it

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
ping @kholk

**Comment by kholk** [comment]
It's a borderline "hack", but since the improvements are NOT negligible..... I would say to accept this.

One day this will not be needed anymore, most probably.

**Comment by Myself5** [comment]
if its not supported on AOSP, why add it? If a ROM supports it the maintainers should be smart enough to enable kryo themselves.

**Comment by alviteri** [comment]
we will add it after tests .... and alin know that

**Pull request closed without merging**
