### PR TITLE
[n-mr1] changes for FBE

### PR DESCRIPTION
**Pull request by jamuir**
adapt the following two upstream commits:
```
  remote: https://source.codeaurora.org/quic/la/device/qcom/sepolicy
  branch: sepolicy.lnx.2.0.r15-rel

  edbf13e sepolicy: added policy fixes for FBE to work properly
  2352ad5 sepolicy: Rename qseecomd policy rules for msm8998
```

### CODE REVIEW

**Comment by jerpelea** [comment]
unless we add the system/bin/init.qti.qseecomd.sh  from qcom there is no reason to add this policy

**Comment by jamuir** [comment]
I will add the sh file in a separate PR.

**Comment by jerpelea** [comment]
regarding first commit 
https://github.com/sonyxperiadev/device-sony-common/blob/master/rootdir/init.common.rc#L77

**Comment by jamuir** [comment]
thanks for the pointer.

We have FBE working in the nougat tree.  It would have been nice to use `wait_for_prop`, but that functionality was only added in oreo.

**Comment by jerpelea** [comment]
cherry-pick it and attach the link here

**Comment by jamuir** [comment]
@jerpelea :  I've pushed a new commit up (22e7e1a9bd) that puts the device in FBE mode, but the PR isn't ready to merge yet.  There is still an issue that I see with the first boot after flashing.  There are more details about it in the commit message.

Also, I am not sure how you feel about enabling FBE mode by default on yoshino.

**Comment by jerpelea** [comment]
I would preffer to have a clean implementation with "wait_for_prop" 
It should need a fiew cherry-picks in system/core

**Comment by Myself5** [comment]
I'd suggest to split the fsmetadata/verity stuff from the FBE lines.
Also, even google is using the sleep way on marlin (and thats even on 8.1) as to be seen here: https://android.googlesource.com/device/google/marlin/+/android-8.1.0_r2/init.qcom.qseecomd.sh

As for the _de crash, I think its caused by `E/vold    (  633): Failed to get encryption policy for /data/data: No such file or directory`. We should figure out whats needed to create /data/data or manually create it, then it should be fine.

The only concearn I have would be that maple is running FDE on stock instead of FBE. We should consider moving the fstab and only enabling FBE for poplar and lilac, in order to support stock -> AOSP transitions (and vice versa) without the need to wipe the complete internal storage. (Other than that it would be huge pain to support both, FDE and FBE in TWRP :P)

**Comment by jamuir** [comment]
For reference, here is a copy of the logcat output from vold when it decides to delete some of the "_de" directories:

```
05-20 05:54:50.731 D/CryptdConnector( 1074): u0 : SND -> {2 cryptfs unlock_user_key 0 0 [scrubbed] [scrubbed]}
05-20 05:54:50.731 D/vold    (  633): e4crypt_unlock_user_key 0 serial=0 token_present=0
05-20 05:54:50.731 W/vold    (  633): Tried to unlock already-unlocked key for user 0
05-20 05:54:50.732 D/CryptdConnector( 1074): u0 : RCV <- {200 2 Command succeeded}
05-20 05:54:50.732 D/CryptdConnector( 1074): u0 : SND -> {3 cryptfs prepare_user_storage ! 0 0 2}
05-20 05:54:50.733 D/vold    (  633): e4crypt_prepare_user_storage for volume null, user 0, serial 0, flags 2
05-20 05:54:50.733 D/vold    (  633): Preparing: /data/system_ce/0
05-20 05:54:50.733 D/vold    (  633): Preparing: /data/misc_ce/0
05-20 05:54:50.733 D/vold    (  633): Preparing: /data/media/0
05-20 05:54:50.733 D/vold    (  633): Preparing: /data/data
05-20 05:54:50.733 I/vold    (  633): Policy for /data/system_ce/0 set to b484c0da4eb17762
05-20 05:54:50.734 I/vold    (  633): Policy for /data/misc_ce/0 set to b484c0da4eb17762
05-20 05:54:50.734 I/vold    (  633): Policy for /data/media/0 set to b484c0da4eb17762
05-20 05:54:50.734 E/vold    (  633): Failed to get encryption policy for /data/data: No such file or directory
05-20 05:54:50.734 E/vold    (  633): Found policy 0000000000000000 at /data/data which doesn't match expected value b484c0da4eb17762
05-20 05:54:50.734 E/vold    (  633): Failed to set policy on: /data/data
05-20 05:54:50.734 D/CryptdConnector( 1074): u0 : RCV <- {400 3 Command failed}
05-20 05:54:50.735 W/PackageManager( 1074): u0 : Destroying user 0 on volume null because we failed to prepare: java.lang.IllegalStateException: command '3 cryptfs prepare_user_storage ! 0 0 2' failed with '400 3 Command failed'
05-20 05:54:50.781 D/CryptdConnector( 1074): u0 : SND -> {4 cryptfs destroy_user_storage ! 0 3}
05-20 05:54:50.782 D/vold    (  633): e4crypt_destroy_user_storage for volume null, user 0, flags 3
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/system/users/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/misc/profiles/cur/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/misc/profiles/cur/0/foreign-dex
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/system_de/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/misc_de/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/user_de/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/system_ce/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/misc_ce/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/media/0
05-20 05:54:50.782 D/vold    (  633): Destroying: /data/data
05-20 05:54:50.782 D/CryptdConnector( 1074): u0 : RCV <- {200 4 Command succeeded}
05-20 05:54:50.783 D/CryptdConnector( 1074): u0 : SND -> {5 cryptfs prepare_user_storage ! 0 0 2}
05-20 05:54:50.783 D/vold    (  633): e4crypt_prepare_user_storage for volume null, user 0, serial 0, flags 2
05-20 05:54:50.783 D/vold    (  633): Preparing: /data/system_ce/0
05-20 05:54:50.783 D/vold    (  633): Preparing: /data/misc_ce/0
05-20 05:54:50.783 D/vold    (  633): Preparing: /data/media/0
05-20 05:54:50.783 D/vold    (  633): Preparing: /data/data
05-20 05:54:50.784 I/vold    (  633): Policy for /data/system_ce/0 set to b484c0da4eb17762
05-20 05:54:50.784 I/vold    (  633): Policy for /data/misc_ce/0 set to b484c0da4eb17762
05-20 05:54:50.785 I/vold    (  633): Policy for /data/media/0 set to b484c0da4eb17762
05-20 05:54:50.785 I/vold    (  633): Policy for /data/data set to b484c0da4eb17762
05-20 05:54:50.785 V/vold    (  633): Starting restorecon of /data/system_ce/0
05-20 05:54:50.787 V/vold    (  633): Finished restorecon of /data/system_ce/0
05-20 05:54:50.787 V/vold    (  633): Starting restorecon of /data/misc_ce/0
05-20 05:54:50.788 V/vold    (  633): Finished restorecon of /data/misc_ce/0
05-20 05:54:50.788 D/CryptdConnector( 1074): u0 : RCV <- {200 5 Command succeeded}
```

**Comment by Myself5** [comment]
So it's destroying all dirs (ce and de) but only recreates the ce ones.

**Comment by Myself5** [comment]
Oh also, what device are you testing this on? I'm still usure maple is going to handle the FBE transition well.

**Comment by jamuir** [comment]
We are using maple.

You're right:  vold destroys and recreates directories but some `de` directories aren't present when PackageManager needs them.

Note that `/data/data` does exist when vold emits the message `Failed to get encryption policy for /data/data: No such file or directory`.  That directory was created by `init` in the `on post-fs-data` section of `init.rc`.

vold is complaining that there was no encryption policy set on `/data/data`.  However, `init` deliberately does not set an encryption policy on that directory, as per the contents of `system/extras/ext4_utils/ext4_crypt_init_extensions.cpp`:

```c
int e4crypt_set_directory_policy(const char* dir)
{
    init_logging();

    // Only set policy on first level /data directories
    // To make this less restrictive, consider using a policy file.
    // However this is overkill for as long as the policy is simply
    // to apply a global policy to all /data folders created via makedir
    if (!dir || strncmp(dir, "/data/", 6) || strchr(dir + 6, '/')) {
        return 0;
    }

    // Special case various directories that must not be encrypted,
    // often because their subdirectories must be encrypted.
    // This isn't a nice way to do this, see b/26641735
    std::vector<std::string> directories_to_exclude = {
        "lost+found",
        "system_ce", "system_de",
        "misc_ce", "misc_de",
        "media",
        "data", "user", "user_de",
    };
    std::string prefix = "/data/";
    for (auto d: directories_to_exclude) {
        if ((prefix + d) == dir) {
            KLOG_INFO(TAG, "Not setting policy on %s\n", dir);
            return 0;
        }
    }
```

**Comment by jamuir** [comment]
@jerpelea :  I will look at adding the `wait_for_prop` patches to `repo_update.sh`.

**Comment by jamuir** [comment]
there is one commit for `wait_for_prop`:

https://android-review.googlesource.com/c/platform/system/core/+/330941

The commit is present in `android-8.0.0_r1`

Unfortunately, it does not apply cleanly (merge conflict for `README.md`), and it needs a number of modifications to make it build in a nougat tree (missing header include; incompatible logging statements).

@jerpelea :  if you really want to use `wait_for_prop` in nougat, then we will need a sony fork of `system/core`.  This type of patching seems too complicated for `repo_update.sh`.

**Comment by jerpelea** [comment]
see what other commits are needed prior this patch to apply it clean

**Comment by jamuir** [comment]
Success!

The first-boot issue (where vold destroys directories) was happening because the directory `/data/data` was not empty.

There was another directory inside it, `/data/data/media`, which was created by a mkdir command in `init.common.rc`:

https://github.com/sonyxperiadev/device-sony-common/blob/n-mr1/rootdir/init.common.rc#L105

the path `/data/data/media` seems like a typo; maybe it should be `/data/media` instead.

In any case, when I drop that line, FBE works fine on first boot.

**Comment by jamuir** [comment]
> please see what other commits are needed prior this patch to apply it clean

@jerpelea:  the `132ac31b4` version of `system/core/init/init.cpp` has diverged substantially from `android-7.1.1_r55`.

Do you have any suggestions on how to determine the needed commits?

**Comment by jerpelea** [comment]
in this case we will use FBE from 8.x

**Comment by jerpelea** [comment]
please split your commit and push the commit to both android 7 and 8 branches

**Comment by jamuir** [comment]
I'm not sure I understand your suggestion.

The current PR contains 4 commits, all pushed to the nougat branch, `n-mr1`.

Do you want me to open a new PR with a subset of the commits?  Which commits?

I haven't built oreo for maple yet.  I would want to do some testing before opening an oreo PR.

**Comment by jamuir** [comment]
added missing `get_prop(init-qti-fbe-sh, tee_prop)` to `init-qti-fbe-sh.te` to address avc denials.

FBE is working in enforcing mode.

**Comment by jerpelea** [comment]
please push o for testing

**Comment by jamuir** [comment]
I've opened two new PRs for oreo:

https://github.com/sonyxperiadev/device-sony-yoshino/pull/70
https://github.com/sonyxperiadev/device-sony-common/pull/391

As mentioned, I have not built an oreo image for maple yet, so these changes are unbuilt and untested.

I think the same kernel is being used on both nougat and oreo, so kernel support for ext4 encryption should be fine.

**Comment by jerpelea** [comment]
thanks

**Comment by jerpelea** [comment]
we do not add new features on Android 7.x

**Comment by jamuir** [comment]
@jerpelea :  aside from `n-mr1`, what is the status of FBE support in the open devices tree?

**Comment by jerpelea** [comment]
We should enable FBE on all devices that come with FBE on the official SW

**Comment by jamuir** [comment]
ok.  That could be encouraging, assuming that there are actually open devices that come with FBE enabled in the official SW :-)

I see that the XZ1 does come with FBE.

And what about the current status of FBE support in the open-device tree?

**Comment by jerpelea** [comment]
don't get me wrong 
we should switch to FBE all yoshino and nile devices

**Comment by Myself5** [comment]
maple uses FDE on stock though, which is why I highly recommend against moving maple to FBE..

**Pull request closed without merging**
