### PR TITLE
[o-mr0] sony: yoshino: init: Move common stuff

### PR DESCRIPTION
**Pull request by humberos**
commonize init stuff

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I725747de71e9a0bb9b15b1526b13ae0eb649a7bf

### CODE REVIEW

**Comment by humberos** [comment]
opss....
it is wrong....
I am removing services....
let me fix it

**Comment by humberos** [comment]
fixed.
ready to be tested

**Comment by humberos** [comment]
Shall I remove max comp streams from platforms?

**Comment by jerpelea** [comment]
i think that we can leave it default

**Comment by jerpelea** [comment]
please remove

**Comment by humberos** [comment]
done

**Pull request merged**
